In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementNotInteractableException
import ipyparallel as ipp

In [2]:
link=pd.read_csv('carwale_links.csv')
link

                                                    url
0     https://www.carwale.com/used/cars-in-noida/hyu...
1     https://www.carwale.com/used/cars-in-delhi/tat...
2     https://www.carwale.com/used/cars-in-noida/hyu...
3     https://www.carwale.com/used/cars-in-faridabad...
4     https://www.carwale.com/used/cars-in-agra/fiat...
...                                                 ...
5024  https://www.carwale.com/used/cars-in-delhi/bmw...
5025  https://www.carwale.com/used/cars-in-delhi/aud...
5026  https://www.carwale.com/used/cars-in-delhi/mer...
5027  https://www.carwale.com/used/cars-in-mohali/hy...
5028  https://www.carwale.com/used/cars-in-delhi/jag...

[5029 rows x 1 columns]

In [6]:
urls=list(link['url'].values[4000:])
year=[]
fuel=[]
kms=[]
owners=[]
transmission=[]
price=[]
mileage=[]
engine=[]
power=[]
seats=[]
gear=[]
drive=[]
steering=[]
torque=[]
values_cylinder=[]
no_cylinder=[]
turbo=[]
super_charger=[]
i=0
driver=webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
for url in urls:
    driver.get(url)
    time.sleep(2)
    while driver.find_element_by_xpath('//li[@data-tabs="specifications"]').text!='Specifications':
        driver.execute_script("window.scrollBy(0,100)")
    powerr=0
    seatss=0
    steeringg=0
    torquee=0
    turboo=0
    superr=0
    gearr=0
    drivee=0
    mileagee=0
    enginee=0
    pricee=0
    yearr=0
    kmss=0
    ownerr=0
    fuell=0
    
    items=driver.find_element_by_xpath('//div[@class="overview-list padding-bottom10"]')
    listy=items.text.split('\n')
    for j in range(len(listy)):
        if listy[j]=='Price':
            price.append(listy[j+1])
            pricee=1
        elif listy[j]=='Year':
            year.append(listy[j+1])
            yearr=1
        elif listy[j]=='Kilometer':
            kms.append(listy[j+1])
            kmss=1
        elif listy[j]=='Fuel Type':
            fuel.append(listy[j+1])
            fuell=1
        elif listy[j]=='No. of Owner(s)':
            owners.append(listy[j+1])
            ownerr=1
            
    button=driver.find_element_by_xpath('//li[@data-tabs="specifications"]')
    button.click()
    
    items=driver.find_element_by_xpath('//div[@class="cw-tabs-data uc-data hide overviewConatiner"]')
    listy=items.text.split('\n')
    
    for j in range(len(listy)):
        if listy[j]=='Engine':
            value=listy[j+1].split(',')
            if len(value)>2:
                values_cylinder.append(value)
                no_cylinder.append(value)
                engine.append(value)
                enginee=1
        elif listy[j]=='Transmission':
            value=listy[j+1].split('-')
            transmission.append(value)
            gear.append(value)
            gearr=1
        elif listy[j]=='Max Power (bhp@rpm)':
            power.append(listy[j+1])
            powerr=1
        elif listy[j]=='Max Torque (Nm@rpm)':
            torque.append(listy[j+1])
            torquee=1
        elif listy[j]=='Mileage (ARAI)':
            mileage.append(listy[j+1])
            mileagee=1
        elif listy[j]=='Drivetrain':
            drive.append(listy[j+1])
            drivee=1
        elif listy[j]=='Turbocharger/Supercharger':
            turbo.append(listy[j+1])
            super_charger.append(listy[j+1])
            turboo=1
        elif listy[j]=='Seating Capacity':
            seats.append(listy[j+1].split()[0])
            seatss=1
        elif listy[j]=='Steering Type':
            steering.append(listy[j+1])
            steeringg=1
    if powerr==0:
        power.append('-')
    if seatss==0:
        seats.append('-')
    if steeringg==0:
        steering.append('-')
    if torquee==0:
        torque.append('-')
    if turboo==0:
        turbo.append('-')
        super_charger.append('-')
    if gearr==0:
        gear.append('-')
        transmission.append('-')
    if drivee==0:
        drive.append('-')
    if enginee==0:
        engine.append('-')
        values_cylinder.append('-')
        no_cylinder.append('-')
    if mileagee==0:
        mileage.append('-')
    if pricee==0:
        price.append('-')
    if yearr==0:
        year.append('-')
    if kmss==0:
        kms.append('-')
    if ownerr==0:
        owner.append('-')
    if fuell==0:
        fuel.append('-')
    
    i+=1
    print(i,end=', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029,

In [14]:
carwale=pd.DataFrame({})
carwale['year']=year
carwale['fuel']=fuel
carwale['kms']=kms
carwale['owners']=owners
carwale['transmission']=transmission
carwale['mileage']=mileage
carwale['engine']=engine
carwale['power']=power
carwale['power_rpm']=0
carwale['seats']=seats
carwale['gear']=gear
carwale['drive']=drive
carwale['steering']=steering
carwale['torque']=torque
carwale['torque_rpm']=0
carwale['values_cylinder']=values_cylinder
carwale['no_cylinder']=no_cylinder
carwale['turbo']=turbo
carwale['super_charger']=super_charger
carwale['price']=price
carwale

,year,fuel,kms,owners,transmission,mileage,engine,power,power_rpm,seats,gear,drive,steering,torque,torque_rpm,values_cylinder,no_cylinder,turbo,super_charger,price
0,Jun 2018,Diesel,"36,000 km",First,"[Automatic , 8 Gears, Paddle Shift, Sport Mode]",-,"[1999 cc, 4 Cylinders Inline, 4 Valves/Cylin...",177 bhp @ 4000 rpm,0,5,"[Automatic , 8 Gears, Paddle Shift, Sport Mode]",AWD,Power assisted (Electric),430 Nm @ 1750 rpm,0,"[1999 cc, 4 Cylinders Inline, 4 Valves/Cylin...","[1999 cc, 4 Cylinders Inline, 4 Valves/Cylin...",Turbocharged,Turbocharged,â‚¹ 62 Lakh
1,Jun 2012,Petrol,"44,473 km",First,"[Manual , 5 Gears]",20.63 kmpl,"[1197 cc, 4 Cylinders Inline, 4 Valves/Cylin...",79 bhp @ 6000 rpm,0,5,"[Manual , 5 Gears]",FWD,-,112.7619 Nm @ 4000 rpm,0,"[1197 cc, 4 Cylinders Inline, 4 Valves/Cylin...","[1197 cc, 4 Cylinders Inline, 4 Valves/Cylin...",-,-,â‚¹ 2.39 Lakh
2,Jun 2016,Petrol,"39,000 km",First,"[AMT , 5 Gears]",20.5 kmpl,"[998 cc, 3 Cylinders Inline, 4 Valves/Cylind...",67 bhp @ 6200 rpm,0,5,"[AMT , 5 Gears]",FWD,Power assisted (Electric),90 Nm @ 3500 rpm,0,"[998 cc, 3 Cylinders Inline, 4 Valves/Cylind...","[998 cc, 3 Cylinders Inline, 4 Valves/Cylind...",No,No,â‚¹ 3.45 Lakh
3,Jun 2017,Petrol,"39,114 km",First,"[Manual , 5 Gears]",18.9 kmpl,"[1197 cc, 4 Cylinders Inline, 4 Valves/Cylin...",81 bhp @ 6000 rpm,0,5,"[Manual , 5 Gears]",FWD,Power assisted (Electric),114 Nm @ 4000 rpm,0,"[1197 cc, 4 Cylinders Inline, 4 Valves/Cylin...","[1197 cc, 4 Cylinders Inline, 4 Valves/Cylin...",No,No,â‚¹ 4.4 Lakh
4,Jan 2013,Diesel,"65,000 km",First,"[Manual , 5 Gears]",-,"[1364 cc, 4 Cylinders Inline, 4 Valves/Cylin...",68 bhp @ 3600 rpm,0,5,"[Manual , 5 Gears]",FWD,-,170 Nm @ 2400 rpm,0,"[1364 cc, 4 Cylinders Inline, 4 Valves/Cylin...","[1364 cc, 4 Cylinders Inline, 4 Valves/Cylin...",-,-,â‚¹ 2.95 Lakh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,Jun 2017,Diesel,"40,000 km",First,"[Automatic , 8 Gears, Paddle Shift, Sport Mode]",18.56 kmpl,"[1995 cc, 4 Cylinders Inline, 4 Valves/Cylin...",190 bhp @ 4000 rpm,0,5,"[Automatic , 8 Gears, Paddle Shift, Sport Mode]",4WD / AWD,Power assisted (Electric),400 Nm @ 1750 rpm,0,"[1995 cc, 4 Cylinders Inline, 4 Valves/Cylin...","[1995 cc, 4 Cylinders Inline, 4 Valves/Cylin...",Turbocharged,Turbocharged,â‚¹ 32.5 Lakh
1025,Jun 2015,Diesel,"14,000 km",First,"[Automatic , CVT Gears, Manual Override, Spor...",16.66 kmpl,"[1968 cc, 4 Cylinders Inline, 4 Valves/Cylin...",177 bhp @ 3750 rpm,0,5,"[Automatic , CVT Gears, Manual Override, Spor...",FWD,Power assisted (Electric),380 Nm @ 1750 rpm,0,"[1968 cc, 4 Cylinders Inline, 4 Valves/Cylin...","[1968 cc, 4 Cylinders Inline, 4 Valves/Cylin...",Turbocharged,Turbocharged,â‚¹ 21.5 Lakh
1026,Jun 2019,Petrol,"15,000 km",First,"[Automatic (Torque Converter) , 9 Gears, Padd...",-,"[1991 cc, 4 Cylinders Inline, 4 Valves/Cylin...",194 bhp @ 5500 rpm,0,5,"[Automatic (Torque Converter) , 9 Gears, Padd...",RWD,Power assisted (Electric),320 Nm @ 1650 rpm,0,"[1991 cc, 4 Cylinders Inline, 4 Valves/Cylin...","[1991 cc, 4 Cylinders Inline, 4 Valves/Cylin...",Turbocharged,Turbocharged,â‚¹ 52.9 Lakh
1027,Jun 2020,Petrol,"15,000 km",First,"[Automatic (Dual Clutch) , 7 Gears, Manual Ov...",17 kmpl,"[1353 cc, 4 Cylinders Inline, 4 Valves/Cylin...",138 bhp @ 6000 rpm,0,5,"[Automatic (Dual Clutch) , 7 Gears, Manual Ov...",FWD,Power assisted (Electric),242 Nm @ 1500 rpm,0,"[1353 cc, 4 Cylinders Inline, 4 Valves/Cylin...","[1353 cc, 4 Cylinders Inline, 4 Valves/Cylin...",Turbocharged,Turbocharged,â‚¹ 19 Lakh
1028,Jun 2017,Diesel,"24,009 km",First,"[Automatic , 8 Gears, Paddle Shift, Sport Mode]",16.38 kmpl,"[1999 cc, 4 Cylinders Inline, 4 Valves/Cylin...",177 bhp @ 4000 rpm,0,5,"[Automatic , 8 Gears, Paddle Shift, Sport Mode]",4WD / AWD,Power assisted (Electric),430 Nm @ 1750 rpm,0,"[1999 cc, 4 Cylinders Inline, 4 Valves/Cylin...","[1999 cc, 4 Cylinders Inline, 4 Valves/Cylin...",Turbocharged,Turbocharged,â‚¹ 41.5 Lakh

In [15]:
for i in range(len(carwale.transmission.values)):
    if carwale.transmission.values[i][0].split()[0]!='AMT':
        carwale['transmission'].iloc[i]=carwale.transmission.values[i][0].split()[0]
    else:
        carwale['transmission'].iloc[i]='Automatic'
for i in range(len(carwale.engine.values)):
    if 'cc' in carwale.engine.values[i][0].split()[:2]:
        carwale['engine'].iloc[i]=int(carwale.engine.values[i][0].split()[0])
    else:
        carwale['engine'].iloc[i]=0
for i in range(len(carwale.gear.values)):
    if carwale.gear.values[i]!='-' and len(carwale.gear.values[i])>1:
        if carwale.gear.values[i][1].split()[0].isdigit():
            carwale['gear'].iloc[i]=int(carwale.gear.values[i][1].split()[0])
        elif carwale.gear.values[i][1].split()[0]=='CVT':
            carwale['gear'].iloc[i]=0
for i in range(len(carwale.steering.values)):
    carwale['steering'].iloc[i]=carwale.steering.values[i].split()[0]
for i in range(len(carwale.no_cylinder.values)):
    if len(carwale.no_cylinder.values[i])>1:
        if carwale.no_cylinder.values[i][1].split()[1]=='Cylinders':
            carwale['no_cylinder'].iloc[i]=carwale.no_cylinder.values[i][1].split()[0]
        else:
            carwale['no_cylinder'].iloc[i]=0
for i in range(len(carwale)):
    updated=0
    if len(carwale.values_cylinder.values[i])>1:
        for j in carwale.values_cylinder.values[i][1:]:
            if len(j.split())>1 and j.split()[1]=='Valves/Cylinder':
                updated=1
                carwale['values_cylinder'].iloc[i]=j.split()[0]
                break
        if updated==0:
            carwale['values_cylinder'].iloc[i]=0
for i in range(len(carwale.super_charger.values)):
    if carwale.super_charger.values[i]=='Yes':
        carwale['super_charger'].iloc[i]=1
    else:
        carwale['super_charger'].iloc[i]=0
for i in range(len(carwale.year.values)):
    carwale['year'].iloc[i]=carwale.year.values[i].split()[1]
for i in range(len(carwale.kms.values)):
    carwale['kms'].iloc[i]=carwale.kms.values[i].split()[0]
for i in range(len(carwale.mileage.values)):
    carwale['mileage'].iloc[i]=carwale.mileage.values[i].split()[0]
for i in range(len(carwale.power.values)):
    if carwale.power.values[i]!='-':
        if carwale.power.values[i].split('@')[1]!='':
            carwale['power_rpm'].iloc[i]=carwale.power.values[i].split('@')[1].split()[0]
            carwale['power'].iloc[i]=carwale.power.values[i].split('@')[0].split()[0]
        elif carwale.power.values[i].split('@')[1]=='':
            carwale['power_rpm'].iloc[i]=0
            carwale['power'].iloc[i]=carwale.power.values[i].split('@')[0].split()[0]
for i in range(len(carwale.torque.values)):
    if carwale.torque.values[i]!='-':
        if carwale.torque.values[i].split('@')[1]!='':
            carwale['torque_rpm'].iloc[i]=carwale.torque.values[i].split('@')[1].split()[0]
            carwale['torque'].iloc[i]=carwale.torque.values[i].split('@')[0].split()[0]
        elif carwale.torque.values[i].split('@')[1]=='':
            carwale['torque_rpm'].iloc[i]=0
            carwale['torque'].iloc[i]=carwale.torque.values[i].split('@')[0].split()[0]
for i in range(len(carwale.price.values)):
    #print(carwale.price.values[i])
    if len(carwale.price.values[i].split())>2:
        if carwale.price.values[i].split()[2]=='Lakh':
            carwale['price'].iloc[i]=int(float(carwale.price.values[i].split()[1])*100000)
        elif carwale.price.values[i].split()[2]=='Crore':
            carwale['price'].iloc[i]=int(float(carwale.price.values[i].split()[1])*10000000)
for i in range(len(carwale.drive.values)):
    if carwale.drive.values[i]=='4WD / AWD':
        carwale['drive'].iloc[i]='AWD'
for i in range(len(carwale.fuel.values)):
    carwale['fuel'].iloc[i]=carwale.fuel.values[i].split()[0]
carwale

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,year,fuel,kms,owners,transmission,mileage,engine,power,power_rpm,seats,gear,drive,steering,torque,torque_rpm,values_cylinder,no_cylinder,turbo,super_charger,price
0,2018,Diesel,"36,000",First,Automatic,-,1999,177,4000,5,8,AWD,Power,430,1750,4,4,1,0,6200000
1,2012,Petrol,"44,473",First,Manual,20.63,1197,79,6000,5,5,FWD,-,112.7619,4000,4,4,1,0,239000
2,2016,Petrol,"39,000",First,Automatic,20.5,998,67,6200,5,5,FWD,Power,90,3500,4,3,1,0,345000
3,2017,Petrol,"39,114",First,Manual,18.9,1197,81,6000,5,5,FWD,Power,114,4000,4,4,1,0,440000
4,2013,Diesel,"65,000",First,Manual,-,1364,68,3600,5,5,FWD,-,170,2400,4,4,1,0,295000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,2017,Diesel,"40,000",First,Automatic,18.56,1995,190,4000,5,8,AWD,Power,400,1750,4,4,1,0,3250000
1025,2015,Diesel,"14,000",First,Automatic,16.66,1968,177,3750,5,0,FWD,Power,380,1750,4,4,1,0,2150000
1026,2019,Petrol,"15,000",First,Automatic,-,1991,194,5500,5,9,RWD,Power,320,1650,4,4,1,0,5290000
1027,2020,Petrol,"15,000",First,Automatic,17,1353,138,6000,5,7,FWD,Power,242,1500,4,4,1,0,1900000
1028,2017,Diesel,"24,009",First,Automatic,16.38,1999,177,4000,5,8,AWD,Power,430,1750,4,4,1,0,4150000

In [16]:
data=pd.read_csv('carwale_data4.csv')
data

,year,fuel,kms,owners,transmission,mileage,engine,power,power_rpm,seats,gear,drive,steering,torque,torque_rpm,values_cylinder,no_cylinder,turbo,super_charger,price
0,2013,Petrol,"64,717",First,Manual,20.3,998,68,6200,5,5,FWD,Power,94,3500,4,3,1,0,229999
1,2019,Petrol,"11,733",First,Manual,23.84,1199,84,6000,5,5,FWD,Power,114,3500,4,3,1,0,475000
2,2016,Petrol,"69,000",First,Manual,19.1,1197,81,6000,5,5,FWD,Power,114,4000,4,4,1,0,395000
3,2016,Diesel,"68,000",First,Automatic,19.6,1461,108,3900,5,6,FWD,Power,248,2250,4,4,1,0,599000
4,2014,Diesel,"76,000",First,Manual,20,1248,90,4000,5,5,FWD,Power,209,2000,4,4,1,0,350000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3964,2014,Diesel,"15,000",First,Manual,23.59,1364,67,3800,5,5,FWD,Power,170,1800,2,4,1,0,400000
3965,2015,Diesel,"45,000",First,Manual,22.7,1498,89,3750,5,5,FWD,Power,204,2000,2,4,1,0,500000
3966,2020,Petrol,"1,485",First,Manual,14.3,1368,160,5500,5,6,FWD,Power,250,2500,4,4,1,0,1425000
3967,2013,Diesel,"22,000",First,Automatic,17.11,1968,177,4200,5,0,FWD,-,380,1750,4,4,1,0,1575000
3968,2013,Petrol,"25,000",Second,Automatic,-,1984,208,4300,2,6,AWD,Power,350,1600,4,4,1,0,2595000

In [17]:
vertical_concat = pd.concat([data,carwale ], axis=0)
vertical_concat

,year,fuel,kms,owners,transmission,mileage,engine,power,power_rpm,seats,gear,drive,steering,torque,torque_rpm,values_cylinder,no_cylinder,turbo,super_charger,price
0,2013,Petrol,"64,717",First,Manual,20.3,998,68,6200,5,5,FWD,Power,94,3500,4,3,1,0,229999
1,2019,Petrol,"11,733",First,Manual,23.84,1199,84,6000,5,5,FWD,Power,114,3500,4,3,1,0,475000
2,2016,Petrol,"69,000",First,Manual,19.1,1197,81,6000,5,5,FWD,Power,114,4000,4,4,1,0,395000
3,2016,Diesel,"68,000",First,Automatic,19.6,1461,108,3900,5,6,FWD,Power,248,2250,4,4,1,0,599000
4,2014,Diesel,"76,000",First,Manual,20,1248,90,4000,5,5,FWD,Power,209,2000,4,4,1,0,350000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,2017,Diesel,"40,000",First,Automatic,18.56,1995,190,4000,5,8,AWD,Power,400,1750,4,4,1,0,3250000
1025,2015,Diesel,"14,000",First,Automatic,16.66,1968,177,3750,5,0,FWD,Power,380,1750,4,4,1,0,2150000
1026,2019,Petrol,"15,000",First,Automatic,-,1991,194,5500,5,9,RWD,Power,320,1650,4,4,1,0,5290000
1027,2020,Petrol,"15,000",First,Automatic,17,1353,138,6000,5,7,FWD,Power,242,1500,4,4,1,0,1900000
1028,2017,Diesel,"24,009",First,Automatic,16.38,1999,177,4000,5,8,AWD,Power,430,1750,4,4,1,0,4150000

In [18]:
vertical_concat.to_csv('carwale_data.csv',index=False)