In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementNotInteractableException
import ipyparallel as ipp

In [11]:
cities=['Chennai','Banglore','Mumbai','Delhi','Hyderabad','Ahemdabad','Kolkata','Surat','Pune','Jaipur','Lucknow','Kanpur',
        'Nagpur','Indore','Thane','Bhopal','Ghaziabad','Agra','Meerut','Aurangabad','Amritsar','Navi Mumbai','Jodhpur',
        'Gurgaon','New Delhi','Noida','Karnataka','Bhiwandi','Kolapur','Ajmer','Udaipur','Pimpri & Chinchwad','Patna',
        'Vadodara','Nashik','Kalyan','Dombivali','Rajkot','Vashi','Allahabad','Coimbatore','Raipur','Kota','Chandigarh',
       'Punjab','Kerala','Amravati']

In [ ]:
urls=[]
i=0
while len(urls)<5000:
    driver=webdriver.Chrome('chromedriver.exe')
    url='https://www.cardekho.com/'
    driver.get(url)
    time.sleep(20)
    button = driver.find_element_by_xpath('/html/body/div[2]/div/header/div[2]/div/div/nav/ul/li[2]/span/span') 
    button.click() 
    time.sleep(20)
    search=driver.find_element_by_xpath('/html/body/div[2]/div/div[3]/div[3]/div/div/div[2]/div[1]/div/div/div/div/input')
    search.clear()
    search.send_keys(cities[i])
    time.sleep(5)
    search.send_keys(Keys.ARROW_DOWN)
    search.click()
    search.send_keys(Keys.ENTER)
    time.sleep(20)
    try:
        button = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div[1]/div[1]/div[2]/div/a') 
        button.click()
        time.sleep(20)
        while driver.find_element_by_xpath('//div[@class="text-center showMoreButton"]/span').text!="That's all folks":
            driver.execute_script("window.scrollBy(0,20)")
        page_urls = driver.find_elements_by_xpath('//div[@class="gsc_col-xs-6  carsName"]/a')
    except:
        while driver.find_element_by_xpath('//div[@class="text-center showMoreButton"]/span').text!="That's all folks":
            driver.execute_script("window.scrollBy(0,20)")
        page_urls = driver.find_elements_by_xpath('//div[@class="gsc_col-xs-7  carsName"]/a')
    for url in page_urls:
        url = url.get_attribute('href')     
        if url[0:4]=='http' and url not in urls:                
            urls.append(url)
    print(cities[i],len(page_urls),len(urls))
    driver.quit()
    i+=1

In [ ]:
links=pd.DataFrame({})
links['url']=urls
links

In [88]:
links.to_csv('cardekho_link.csv', index = True)

In [3]:
link=pd.read_csv('cardekho_link.csv')
link

      Unnamed: 0                                                url
0              0  https://www.cardekho.com/used-car-details/used...
1              1  https://www.cardekho.com/used-car-details/used...
2              2  https://www.cardekho.com/used-car-details/used...
3              3  https://www.cardekho.com/used-car-details/used...
4              4  https://www.cardekho.com/used-car-details/used...
...          ...                                                ...
5098        5098  https://www.cardekho.com/used-car-details/used...
5099        5099  https://www.cardekho.com/used-car-details/used...
5100        5100  https://www.cardekho.com/used-car-details/used...
5101        5101  https://www.cardekho.com/used-car-details/used...
5102        5102  https://www.cardekho.com/used-car-details/used...

[5103 rows x 2 columns]

In [7]:
urls=list(link['url'].values[:1000])
#urls=['https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Vxi-cars-Bangalore_ef3284f6-26bf-4793-8223-7120255389ae.htm']
year=[]
fuel=[]
kms=[]
owners=[]
transmission=[]
price=[]
mileage=[]
engine=[]
power=[]
seats=[]
gear=[]
drive=[]
steering=[]
torque=[]
values_cylinder=[]
no_cylinder=[]
turbo=[]
super_charger=[]
i=0
ui=0
driver=webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
for url in urls:
    driver.get(url)
    time.sleep(3)
    driver.execute_script("window.scrollBy(0,1000)")
    time.sleep(2)
    driver.execute_script("window.scrollBy(0,500)")
    time.sleep(2)
    try:
        if driver.find_element_by_xpath('//div[@class="hover whatsappShare margt25 shareButton"]').text=='View All Specifications':
            button=driver.find_element_by_xpath('//div[@class="hover whatsappShare margt25 shareButton"]')
            button.click()
            ui=0
            time.sleep(2) 
        else:
            raise NoSuchElementException
    except:
        try:
            view=driver.find_element_by_xpath('//a[@class=" viewMorebtn viewMorebtnArrow"]')
            view.click()
            ui=1
            time.sleep(2) 
        except:
            try:
                view=driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div[2]/div[1]/div/div[4]/div/div/div/div/div[2]/a')
                view.click()
                ui=1
                time.sleep(2)
            except NoSuchElementException:
                i+=1
                continue
        #--year--
    try:
        ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[2]/div/div[2]')      
        year.append(ear.text)
    except NoSuchElementException:
        try:
            ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div[2]/div[1]/div/div[3]/div/div/div/div[1]/ul/li[1]/div/div')      
            year.append(ear.text) 
        except:
            year.append('-')
        #--fuel--
    try:
        ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[3]/div/div[2]')      
        fuel.append(ear.text)
    except NoSuchElementException:
        try:
            ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div[2]/div[1]/div/div[3]/div/div/div/div[1]/ul/li[5]/div/div') 
            fuel.append(ear.text) 
        except:
            fuel.append('-')
    #--kms--
    try:
        ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[4]/div/div[2]')      
        kms.append(ear.text)
    except NoSuchElementException:
        try:
            ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div[2]/div[1]/div/div[3]/div/div/div/div[1]/ul/li[3]/div/div') 
            kms.append(ear.text) 
        except:
            kms.append('-')
    #--owners--
    try:
        ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[6]/div/div[2]')      
        owners.append(ear.text)
    except NoSuchElementException:
        try:
            ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div[2]/div[1]/div/div[3]/div/div/div/div[1]/ul/li[4]/div/div') 
            owners.append(ear.text) 
        except:
            owners.append('-')
    #--transmission--
    try:
        ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[8]/div/div[2]')      
        transmission.append(ear.text)
    except NoSuchElementException:
        try:
            ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div[2]/div[1]/div/div[3]/div/div/div/div[1]/ul/li[6]/div/div') 
            transmission.append(ear.text) 
        except:
            transmission.append('-')
    #--price--
    try:
        ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[2]/div/div[1]/span[2]')      
        price.append(ear.text)
    except NoSuchElementException:
        try:
            ear = driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/div/div/main/div[2]/div[1]/div/div[2]/div[2]/div/div/div/div[1]/span/span') 
            price.append(ear.text) 
        except:
            price.append('-')
    if ui==0:
        items=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6 gsc_col-md-4"]')
        first=0
        powerr=0
        seatss=0
        steeringg=0
        torquee=0
        ncy=0
        vcy=0
        turboo=0
        superr=0
        gearr=0
        drivee=0
        mileagee=0
        enginee=0
        for j in range(len(items)):
            if len(items[j].text.split())>1:
                #print(items[j].text.split())
                if items[j].text.split()[1]=='Power' and first==0:
                    first=1
                    continue
                elif len(items[j].text.split())>2 and items[j].text.split()[1]=='Power' and first==1:
                    power.append(items[j].text.split()[2])
                    powerr=1
                elif items[j].text.split()[0]=='Seats':
                    seats.append(items[j].text.split()[1])
                    seatss=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Steering':
                    steering.append(items[j].text.split()[2])
                    steeringg=1
                elif len(items[j].text.split())>2 and items[j].text.split()[1]=='Torque':
                    torque.append(items[j].text.split()[2])
                    torquee=1
                elif len(items[j].text.split())>3 and items[j].text.split()[0]=='No' and items[j].text.split()[2]=='Cylinder':
                    no_cylinder.append(items[j].text.split()[3])
                    ncy=1
                elif len(items[j].text.split())>3 and items[j].text.split()[0]=='Values':
                    values_cylinder.append(items[j].text.split()[3])
                    vcy=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Turbo':
                    turbo.append(items[j].text.split()[2])
                    turboo=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Super':
                    super_charger.append(items[j].text.split()[2])
                    superr=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Gear':
                    gear.append(items[j].text.split()[2])
                    gearr=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Drive':
                    drive.append(items[j].text.split()[2])
                    drivee=1
                elif items[j].text.split()[0]=='Mileage':
                    mileage.append(items[j].text.split()[1])
                    engine.append(items[j+1].text.split()[1])
                    mileagee=1
                    enginee=1

        if powerr==0:
            power.append('-')
        if seatss==0:
            seats.append('-')
        if steeringg==0:
            steering.append('-')
        if torquee==0:
            torque.append('-')
        if ncy==0:
            no_cylinder.append('-')
        if vcy==0:
            values_cylinder.append('-')
        if turboo==0:
            turbo.append('-')
        if superr==0:
            super_charger.append('-')
        if gearr==0:
            gear.append('-')
        if drivee==0:
            drive.append('-')
        if enginee==0:
            engine.append('-')
        if mileagee==0:
            mileage.append('-')
    elif ui==1:
        items=driver.find_elements_by_xpath('//li[@class="gsc_col-xs-6"]')
        first=0
        powerr=0
        seatss=0
        steeringg=0
        torquee=0
        ncy=0
        vcy=0
        turboo=0
        superr=0
        gearr=0
        drivee=0
        mileagee=0
        enginee=0
        for j in range(len(items)):
            if len(items[j].text.split())>1:
                if items[j].text.split()[0]=='Seats':
                    seats.append(items[j].text.split()[1])
                    seatss=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Steering':
                    steering.append(items[j].text.split()[2])
                    steeringg=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Max' and items[j].text.split()[1]=='Torque':
                    torque.append(''.join(items[j].text.split()[2:]))
                    power.append(''.join(items[j-1].text.split()[2:]))
                    powerr=1
                    torquee=1
                elif len(items[j].text.split())>3 and items[j].text.split()[0]=='No' and items[j].text.split()[2]=='Cylinder':
                    no_cylinder.append(items[j].text.split()[3])
                    ncy=1
                elif len(items[j].text.split())>3 and items[j].text.split()[0]=='Valves':
                    values_cylinder.append(items[j].text.split()[3])
                    vcy=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Turbo':
                    turbo.append(items[j].text.split()[2])
                    turboo=1
                elif items[j].text.split()[0]=='superCharger':
                    super_charger.append(items[j].text.split()[1])
                    superr=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Gear':
                    gear.append(items[j].text.split()[2])
                    gearr=1
                elif len(items[j].text.split())>2 and items[j].text.split()[0]=='Drive':
                    drive.append(items[j].text.split()[2])
                    drivee=1
                elif items[j].text.split()[0]=='Mileage':
                    mileage.append(items[j].text.split()[1])
                    engine.append(items[j+1].text.split()[1])
                    mileagee=1
                    enginee=1 
        if powerr==0:
            power.append('-')
        if seatss==0:
            seats.append('-')
        if steeringg==0:
            steering.append('-')
        if torquee==0:
            torque.append('-')
        if ncy==0:
            no_cylinder.append('-')
        if vcy==0:
            values_cylinder.append('-')
        if turboo==0:
            turbo.append('-')
        if superr==0:
            super_charger.append('-')
        if gearr==0:
            gear.append('-')
        if drivee==0:
            drive.append('-')
        if enginee==0:
            engine.append('-')
        if mileagee==0:
            mileage.append('-')
    i+=1
    print(i,end=', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000,

In [8]:
cardekho=pd.DataFrame({})
cardekho['year']=year
cardekho['fuel']=fuel
cardekho['kms']=kms
cardekho['owners']=owners
cardekho['transmission']=transmission
cardekho['mileage']=mileage
cardekho['engine']=engine
cardekho['power']=power
cardekho['seats']=seats
cardekho['gear']=gear
cardekho['drive']=drive
cardekho['steering']=steering
cardekho['torque']=torque
cardekho['values_cylinder']=values_cylinder
cardekho['no_cylinder']=no_cylinder
cardekho['turbo']=turbo
cardekho['super_charger']=super_charger
cardekho['price']=price
cardekho

,year,fuel,kms,owners,transmission,mileage,engine,power,seats,gear,drive,steering,torque,values_cylinder,no_cylinder,turbo,super_charger,price
0,1995,Diesel,"35,000 kms",Fourth & Above Owner,Manual,0.0,2112,null,6,-,-,Power,null,4,4,null,null,2.15 Lakh*
1,2016,Diesel,"1,20,000 kms",First Owner,Manual,28.09,1248,88.5bhp@4000rpm,5,5,FWD,Power,200Nm@1750rpm,4,4,Yes,No,7 Lakh*
2,2014,Petrol,"60,000 kms",Second Owner,Manual,16.51,1586,103.2bhp@5600rpm,5,5,FWD,Power,145Nm@4100rpm,4,4,No,No,3.15 Lakh*
3,2017,Petrol,"40,000 kms",First Owner,Manual,21.21,1197,81.80bhp@6000rpm,5,5,FWD,Power,113Nm@4200rpm,4,4,No,No,5.8 Lakh*
4,2018,Petrol,"46,000 kms",First Owner,Manual,23.1,998,67.04bhp@6000rpm,5,5,FWD,Power,90Nm@3500rpm,4,3,No,No,4.1 Lakh*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,Jan 2018,Petrol,"33,120 Kms",1st Owner,Manual,20.89,1197,81.80bhp@6000rpm,5,5,FWD,Electrical,113Nm@4200rpm,4,4,No,No,"5,58,500"
991,Jul 2008,Petrol,"43,582 Kms",2nd Owner,Manual,19.81,1086,68.05bhp@5500rpm,5,5,FWD,Power,99.04Nm@4500rpm,3,4,No,No,"2,41,000"
992,Jan 2013,Petrol,"38,898 Kms",2nd Owner,Manual,17,1197,80,5,5,-,Power,11.4,4,4,No,No,"4,39,500"
993,Jul 2011,Petrol,"76,797 Kms",2nd Owner,Automatic,16.95,1197,78.9bhp@6000rpm,5,4-Speed,FWD,Power,111.8Nm@4000rpm,4,4,No,No,"3,43,000"
994,Dec 2018,Petrol,"24,464 Kms",1st Owner,Automatic,22,999,67bhp@5500rpm,5,5,FWD,Electric,91Nm@4250rpm,4,3,No,No,"4,77,000"

In [9]:
cardekho.to_csv('cardekho.csv')

In [11]:
data=pd.read_csv('cardekho_data.csv')
data

,year,fuel,kms,owners,transmission,mileage,engine,power,seats,gear,drive,steering,torque,values_cylinder,no_cylinder,turbo,super_charger,price
0,1995,Diesel,"35,000 kms",Fourth & Above Owner,Manual,0.0,2112,NaN,6,-,-,Power,NaN,4,4,NaN,NaN,2.15 Lakh*
1,2016,Diesel,"1,20,000 kms",First Owner,Manual,28.09,1248,88.5bhp@4000rpm,5,5,FWD,Power,200Nm@1750rpm,4,4,Yes,No,7 Lakh*
2,2014,Petrol,"60,000 kms",Second Owner,Manual,16.51,1586,103.2bhp@5600rpm,5,5,FWD,Power,145Nm@4100rpm,4,4,No,No,3.15 Lakh*
3,2017,Petrol,"40,000 kms",First Owner,Manual,21.21,1197,81.80bhp@6000rpm,5,5,FWD,Power,113Nm@4200rpm,4,4,No,No,5.8 Lakh*
4,2018,Petrol,"46,000 kms",First Owner,Manual,23.1,998,67.04bhp@6000rpm,5,5,FWD,Power,90Nm@3500rpm,4,3,No,No,4.1 Lakh*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5049,2005,Diesel,"85,000 kms",Third Owner,Manual,0.0,2523,50bhp@3000rpm,10,-,-,Manual,145Nm@1800rpm,2,4,Yes,NaN,2.25 Lakh*
5050,2011,Diesel,"1,20,000 kms",Second Owner,Manual,11.5,2982,171PS@3600rpm,7,5,4WD,Power,343Nm@1400-3400rpm,4,4,Yes,No,10.5 Lakh*
5051,2013,Diesel,"61,660 kms",First Owner,Manual,14.02,2179,118.3bhp@4000rpm,8,5,RWD,Power,280Nm@2400-2800rpm,4,4,No,No,4.95 Lakh*
5052,2016,Petrol,"44,457 kms",Second Owner,Automatic,17.21,1197,103.5bhp@5000rpm,5,7,FWD,Power,175Nm@1500-4100rpm,4,4,Yes,No,5.99 Lakh*
5053,2021,Petrol,"5,000 kms",First Owner,Manual,23.26,1197,88.50bhp@6000rpm,5,5,FWD,Electric,113nm@4400rpm,4,4,No,No,7 Lakh*

In [12]:
data['power_rpm']=0
data['torque_rpm']=0
for i in range(len(data.kms.values)):
    data['kms'].iloc[i]=data.kms.values[i].split()[0]
    if ''.join(data.kms.values[i].split(',')).isdigit():
        data['kms'].iloc[i]=int(''.join(data.kms.values[i].split(',')))
for i in range(len(data.owners.values)):
    if data.owners.values[i].split()[1]=='&':
        data['owners'].iloc[i]=data.owners.values[i].split()[0]+'+'
    else:
        data['owners'].iloc[i]=data.owners.values[i].split()[0]
for i in range(len(data.drive.values)):
    if data.drive.values[i]=='2' or data.drive.values[i]=='2WD' or data.drive.values[i]=='2wd' or data.drive.values[i]=='Two' or data.drive.values[i]=='4X2' or data.drive.values[i]=='Front':
        data.iloc[i]='FWD'
    elif data.drive.values[i]=='4WD' or data.drive.values[i]=='4X4' or data.drive.values[i]=='All' or data.drive.values[i]=='All-wheel':
        data.iloc[i]='AWD'
    elif data.drive.values[i]=='Rear':
        data.iloc[i]='RWD'
for i in range(len(data.power.values)):
    try:
        if len(data.power.values[i].split('@'))==1 and len(data.power.values[i].split('PSat'))==1:
            data['power'].iloc[i]=0
        else:
            data['power_rpm'].iloc[i]=data.power.values[i].split('@')[1]
            data['power'].iloc[i]=data.power.values[i].split('@')[0]
    except:
        data['power'].iloc[i]=0
        data['power_rpm'].iloc[i]=0
for i in range(len(data.power.values)):
    try:
        if data.power.values[i][-3:].lower()=='bhp':
            data['power'].iloc[i]=float(data.power.values[i][:-3])
        elif data.power.values[i][-2:]=='PS':
            data['power'].iloc[i]=float(data.power.values[i][:-2])
    except:
        pass
for i in range(len(data.power_rpm.values)):
    try:
        if data.power_rpm.values[i][-3:].lower()=='rpm' or data.power_rpm.values[i][-3:].lower()=='prm':
            data['power_rpm'].iloc[i]=float(data.power_rpm.values[i][:-3])
        else:
            if data.power_rpm.values[i]=='FWD' or data.power_rpm.values[i]=='AWD' or data.power_rpm.values[i]=='RWD':
                data['power_rpm'].iloc[i]=0
            else:
                if data['power_rpm'].iloc[i].split('(')[0].isdigit():
                    data['power_rpm'].iloc[i]=data['power_rpm'].values[i].split('(')[0]
                else:
                    if ''.join(data['power_rpm'].iloc[i].split(',')[0]).isdigit():
                        data['power_rpm'].iloc[i]=''.join(data['power_rpm'].iloc[i].split(',')[0])
                    else:
                        data['power_rpm'].iloc[i]=data.power_rpm.values[i].split('-')[0]
                        
    except:
        if data.power_rpm.values[i]=='FWD' or data.power_rpm.values[i]=='AWD':
            data['power_rpm'].iloc[i]=0
for i in range(len(data.torque.values)):
    try:
        if len(data.torque.values[i].split('@'))==1:# and len(data.torque.values[i].split('PSat'))==1:
            data['torque'].iloc[i]=0
        else:
            data['torque_rpm'].iloc[i]=data.torque.values[i].split('@')[1]
            data['torque'].iloc[i]=data.torque.values[i].split('@')[0]
    except:
        data['torque'].iloc[i]=0
        data['torque_rpm'].iloc[i]=0
for i in range(len(data.torque.values)):
    try:
        if data.torque.values[i][-2:].lower()=='nm':
            data['torque'].iloc[i]=data.torque.values[i][:-2]
        elif data.torque.values[i][-3:].lower()=='kgm':
            data['torque'].iloc[i]=data.torque.values[i][:-3]
        elif data.torque.values[i][-4:].lower()=='kg-m':
            data['torque'].iloc[i]=data.torque.values[i][:-4]
    except:
        pass
for i in range(len(data.torque_rpm.values)):
    try:
        if data.torque_rpm.values[i][-3:]=='rpm':
            data['torque_rpm'].iloc[i]=data.torque_rpm.values[i][:-3]
        elif data.torque_rpm.values[i]=='FWD' or data.torque_rpm.values[i]=='AWD' or data.torque_rpm.values[i]=='RWD':
            data['torque_rpm'].iloc[i]=0 
        elif data.torque_rpm.values[i][-4:]=='(kgm':
            data['torque_rpm'].iloc[i]=data.torque_rpm.values[i][:-4]
        if ''.join(data['torque_rpm'].iloc[i].split(',')[0]).isdigit():
            data['torque_rpm'].iloc[i]=''.join(data['torque_rpm'].iloc[i].split(',')[0])
        if len(data.torque_rpm.values[i].split('-'))>1:
            if data.torque_rpm.values[i].split('-')[1][-3:]=='(NM':
                data['torque_rpm'].iloc[i]=data.torque_rpm.values[i].split('-')[1][:-3]
            else:
                data['torque_rpm'].iloc[i]=data.torque_rpm.values[i].split('-')[1]
        if ''.join(data['torque_rpm'].iloc[i].split(',')[0]).isdigit():
            data['torque_rpm'].iloc[i]=''.join(data['torque_rpm'].iloc[i].split(',')[0])
    except:
        pass
for i in range(len(data.price.values)):
    if data.price.values[i][-5:]=='Lakh*':
        data['price'].iloc[i]=float(data.price.values[i].split()[0])*100000
    elif data.price.values[i]=='FWD' or data.price.values[i]=='AWD' or data.price.values[i]=='RWD':
        data['price'].iloc[i]=0  
    elif data.price.values[i][-1]=='*':
        data['price'].iloc[i]=data['price'].iloc[i][:-1]
    elif ''.join(data.price.values[i].split(',')).isdigit():
        data['price'].iloc[i]=float(''.join(data.price.values[i].split(',')))
dropp=[]
for i in range(len(data['year'].values)):
    try:
        data['year'].iloc[i]=int(data['year'].values[i])
    except:
        if data.year.values[i]=='FWD' or data.year.values[i]=='AWD' or data.year.values[i]=='RWD':
            dropp.append(i)
        else:
            try:
                data['year'].iloc[i]=int(data['year'].values[i].split()[1])
            except:
                print(data['year'].values[i])
data=data.drop(data.index[dropp])
data=data[['year', 'fuel', 'kms', 'owners', 'transmission', 'mileage', 'engine','power','power_rpm', 'seats', 'gear', 'drive', 'steering', 'torque','torque_rpm','values_cylinder', 'no_cylinder', 'turbo', 'super_charger', 'price']]
data=data.reset_index(drop=True)
for i in range(len(data.gear.values)):
    if len(data.gear.values[i].split('-'))>1:
        data['gear'].iloc[i]=data.gear.values[i].split('-')[0]
    elif data.gear.values[i]=='CVT' or data.gear.values[i]=='AGS' or data.gear.values[i]=='iMT':
        data['gear'].iloc[i]=0
    elif data.gear.values[i][-1]=='G':
        data['gear'].iloc[i]=data.gear.values[i][:-1]
data=data.drop(['super_charger'],axis=1)

data

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,year,fuel,kms,owners,transmission,mileage,engine,power,power_rpm,seats,gear,drive,steering,torque,torque_rpm,values_cylinder,no_cylinder,turbo,price
0,1995,Diesel,35000,Fourth+,Manual,0.0,2112,0,0,6,,-,Power,0,0,4,4,NaN,215000.0
1,2016,Diesel,120000,First,Manual,28.09,1248,88.5,4000.0,5,5,FWD,Power,200,1750,4,4,Yes,700000.0
2,2014,Petrol,60000,Second,Manual,16.51,1586,103.2,5600.0,5,5,FWD,Power,145,4100,4,4,No,315000.0
3,2017,Petrol,40000,First,Manual,21.21,1197,81.8,6000.0,5,5,FWD,Power,113,4200,4,4,No,580000.0
4,2018,Petrol,46000,First,Manual,23.1,998,67.04,6000.0,5,5,FWD,Power,90,3500,4,3,No,410000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,2013,Petrol,45000,Second,Automatic,16.95,1197,78.9,6000.0,5,4,FWD,Power,111.8,4000,4,4,No,300000.0
4805,2005,Diesel,85000,Third,Manual,0.0,2523,50.0,3000.0,10,,-,Manual,145,1800,2,4,Yes,225000.0
4806,2013,Diesel,61660,First,Manual,14.02,2179,118.3,4000.0,8,5,RWD,Power,280,2800,4,4,No,495000.0
4807,2016,Petrol,44457,Second,Automatic,17.21,1197,103.5,5000.0,5,7,FWD,Power,175,4100,4,4,Yes,599000.0
4808,2021,Petrol,5000,First,Manual,23.26,1197,88.5,6000.0,5,5,FWD,Electric,113,4400,4,4,No,700000.0

In [145]:
data.owners.value_counts()

First      2046
1st        1853
Second      484
2nd         343
Third        70
Fourth+       9
3rd           4
Name: owners, dtype: int64

In [13]:
for i in range(len(data.owners.values)):
    if data.owners.values[i]=='1st' or data.owners.values[i]=='First':
        data['owners'].iloc[i]=1
    elif data.owners.values[i]=='2nd' or data.owners.values[i]=='Second':
        data['owners'].iloc[i]=2
    elif data.owners.values[i]=='3rd' or data.owners.values[i]=='Third':
        data['owners'].iloc[i]=3
    elif data.owners.values[i]=='Fourth+':
        data['owners'].iloc[i]=4

In [146]:
data.transmission.value_counts()

Manual       3855
Automatic     846
MH12            7
RJ14            7
MH01            6
MH04            5
MH43            5
DL3C            4
DL9C            3
MH05            3
KA03            3
DL5C            3
MH02            3
MH03            3
HR87            3
KA04            3
HR29            3
DL10            2
KA01            2
MH46            2
RJ45            2
KA05            2
UP14            2
DL2C            2
DL6C            2
MH47            2
KA02            2
UP16            2
MH48            2
HR26            2
TS08            2
DL1C            2
HR51            2
KA53            2
DL12            1
AP09            1
UP32            1
AP36            1
KA50            1
MH29            1
HR77            1
MH14            1
TS10            1
AP23            1
MH11            1
HR10            1
KA19            1
Name: transmission, dtype: int64

In [14]:
for i in range(len(data.transmission.values)):
    if data.transmission.values[i]=='Manual' or data.transmission.values[i]=='Automatic':
        pass
    else:
        data['transmission'].iloc[i]=0

In [152]:
data.steering.value_counts()

Power         4335
Electric       316
Manual          72
Electrical      47
-               17
Electronic       9
EPAS             9
Hydraulic        4
Name: steering, dtype: int64

In [15]:
for i in range(len(data.steering.values)):
    if data.steering.values[i]=='Manual' or data.steering.values[i]=='-':
        pass
    else:
        data['steering'].iloc[i]='Power'

In [16]:
data.to_csv('carwale_data_final.csv',index=False)

In [17]:
carwale=pd.read_csv('carwale_data.csv')

In [18]:
vertical_concat = pd.concat([data,carwale ], axis=0)
vertical_concat

,year,fuel,kms,owners,transmission,mileage,engine,power,power_rpm,seats,gear,drive,steering,torque,torque_rpm,values_cylinder,no_cylinder,turbo,price
0,1995,Diesel,35000,4,Manual,0.0,2112,0,0,6,,-,Power,0,0,4,4,NaN,215000.0
1,2016,Diesel,120000,1,Manual,28.09,1248,88.5,4000.0,5,5,FWD,Power,200,1750,4,4,Yes,700000.0
2,2014,Petrol,60000,2,Manual,16.51,1586,103.2,5600.0,5,5,FWD,Power,145,4100,4,4,No,315000.0
3,2017,Petrol,40000,1,Manual,21.21,1197,81.8,6000.0,5,5,FWD,Power,113,4200,4,4,No,580000.0
4,2018,Petrol,46000,1,Manual,23.1,998,67.04,6000.0,5,5,FWD,Power,90,3500,4,3,No,410000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993,2017,Diesel,40000.0,First,Automatic,18.56,1995,190,4000,5,8,AWD,Power,400,1750,4,4,1,3250000
4994,2015,Diesel,14000.0,First,Automatic,16.66,1968,177,3750,5,0,FWD,Power,380,1750,4,4,1,2150000
4995,2019,Petrol,15000.0,First,Automatic,-,1991,194,5500,5,9,RWD,Power,320,1650,4,4,1,5290000
4996,2020,Petrol,15000.0,First,Automatic,17,1353,138,6000,5,7,FWD,Power,242,1500,4,4,1,1900000
4997,2017,Diesel,24009.0,First,Automatic,16.38,1999,177,4000,5,8,AWD,Power,430,1750,4,4,1,4150000

In [20]:
vertical_concat=vertical_concat.drop(['turbo'],axis=1)

In [21]:
vertical_concat.to_csv('car_data.csv',index=False)